### ISSUE TITLE
데이터 관련 질문

### ISSUE THREAD

**Issue by yjhong89** [etri/kmsav#1]
안녕하세요, 데이터 공유 감사드리며, 몇 가지 질문이 있습니다.

- https://github.com/etri/kmsav/blob/main/data/list.txt 여기에 있는 datalist와 ASD info file (v0.2) 에 있는 datalist가 숫자가 많이 차이가 나는데요, (ASD info file 에 509개) 
- ASD info file에 속하지 않은 data/list.txt 안의 동영상은 crop, trim 에 필요한 메타 정보가 없을까요??

감사합니다!

**Comment by yjhong89** [comment]
ASD info file의 crop 정보도 잘못된 것 같습니다.
- zu1REHalroU 동영상에 대해서 16.txt를 이용해 crop 했을 때, 다음처럼 얼굴이 아닌 다른 부분이 crop 됩니다.

- 원본 이미지
![003873](https://github.com/user-attachments/assets/d9794e3e-2023-4e12-be85-7de72ef55a0c)
- Cropped
![003873 jpg_cropped](https://github.com/user-attachments/assets/8e805b55-afff-4a57-a72d-e3af09531046)

- 최종 cropped + audio mp4


https://github.com/user-attachments/assets/dbc57052-2746-4c5b-a7b4-f3b5093ef48e

**Comment by pkyoung** [comment]
* 제공된 스크립트 파일이 (ASD info file의 crop 정보 포함) 원본 동영상 파일이 1280x720 의 해상도인경우에 동작하는 것으로 확인되었습니다. 이에 따라 원본  영상의 download 방법을 문서에 수정했습니다. 참고하세요(8a96a7d)
* data/list.txt 중 pretrain에 해당되는 것은 manual 전사가 없어서 현재는 crop 정보도 없는 상태입니다.
* 조만간 자동으로 생성된 crop 정보를 추가할 예정입니다.
